import { escapeHtml, statusEmoji, isoDate } from '../lib/format.js';

// sources: [{ id, label, configured, note, perProject }]
export function buildWeekly({ projects, sources }) {
  const date = isoDate();
  const configured = sources.filter((s) => s.configured);
  const notConfigured = sources.filter((s) => !s.configured);

  // Collect "needs attention" rows (bad/warn) for the priority section.
  const attention = [];
  for (const p of projects) {
    for (const s of configured) {
      const cell = s.perProject[p.key];
      if (cell && (cell.level === 'bad' || cell.level === 'warn')) {
        attention.push({ project: p.name, source: s.label, level: cell.level, summary: cell.summary });
      }
    }
  }
  attention.sort((a, b) => (a.level === 'bad' ? -1 : 1) - (b.level === 'bad' ? -1 : 1));

  const cols = configured;
  const headCells = cols.map((s) => `<th style="text-align:left;padding:6px 10px;border-bottom:2px solid #ddd">${escapeHtml(s.label)}</th>`).join('');
  const rows = projects
    .map((p) => {
      const cells = cols
        .map((s) => {
          const c = s.perProject[p.key] || { level: 'na', summary: '—' };
          return `<td style="padding:6px 10px;border-bottom:1px solid #eee;white-space:nowrap">${statusEmoji(c.level)} ${escapeHtml(c.summary)}</td>`;
        })
        .join('');
      return `<tr><td style="padding:6px 10px;border-bottom:1px solid #eee;font-weight:600">${escapeHtml(p.name)}</td>${cells}</tr>`;
    })
    .join('');

  const attentionHtml = attention.length
    ? `<ul>${attention.map((a) => `<li>${statusEmoji(a.level)} <b>${escapeHtml(a.project)}</b> — ${escapeHtml(a.source)}: ${escapeHtml(a.summary)}</li>`).join('')}</ul>`
    : `<p>🟢 Nothing urgent this week.</p>`;

  const notConfiguredHtml = notConfigured.length
    ? `<p style="color:#888;font-size:13px">Not configured: ${notConfigured.map((s) => `${escapeHtml(s.label)}${s.note ? ` (${escapeHtml(s.note)})` : ''}`).join('; ')}</p>`
    : '';

  const html = `<!doctype html><html><body style="font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#222;max-width:900px">
  <h2>Weekly ops report — ${date}</h2>
  <h3>Needs attention</h3>
  ${attentionHtml}
  <h3>All projects</h3>
  <table style="border-collapse:collapse;font-size:13px"><thead><tr><th style="text-align:left;padding:6px 10px;border-bottom:2px solid #ddd">Project</th>${headCells}</tr></thead><tbody>${rows}</tbody></table>
  ${notConfiguredHtml}
  <p style="color:#aaa;font-size:12px">Generated by ops-monitoring · ${date}</p>
  </body></html>`;

  const text =
    `Weekly ops report — ${date}\n\nNeeds attention:\n` +
    (attention.length ? attention.map((a) => `- [${a.level}] ${a.project} — ${a.source}: ${a.summary}`).join('\n') : 'Nothing urgent.') +
    `\n`;

  return { subject: `Weekly ops report — ${date}${attention.some((a) => a.level === 'bad') ? ' ⚠️' : ''}`, html, text, attention };
}
